### ISSUE TITLE
Create Documentation for Groups and SubGroups

### ISSUE THREAD

**Issue by mrdrewkeller** [Johns2MW/drupal-demonstration#38]

**Comment by Johns2MW** [comment]
![1](https://cloud.githubusercontent.com/assets/19668228/15941150/db612d60-2e4c-11e6-8e56-a31073535e41.PNG)
![2](https://cloud.githubusercontent.com/assets/19668228/15941155/db6a4c24-2e4c-11e6-95e5-42c687bdcd0a.PNG)
![2a](https://cloud.githubusercontent.com/assets/19668228/15941158/db7243fc-2e4c-11e6-9065-ed65de78b728.PNG)
![3](https://cloud.githubusercontent.com/assets/19668228/15941153/db682fb6-2e4c-11e6-931d-859bc11ae348.PNG)
![4](https://cloud.githubusercontent.com/assets/19668228/15941151/db677044-2e4c-11e6-92a5-948f7d6fa51d.PNG)
![5](https://cloud.githubusercontent.com/assets/19668228/15941152/db681b66-2e4c-11e6-8880-94bbb25e2279.PNG)
![6](https://cloud.githubusercontent.com/assets/19668228/15941154/db684992-2e4c-11e6-872a-6271f3bf81b6.PNG)
![7](https://cloud.githubusercontent.com/assets/19668228/15941161/db770720-2e4c-11e6-805c-43a9c005e8a5.PNG)
![8](https://cloud.githubusercontent.com/assets/19668228/15941160/db744292-2e4c-11e6-9e10-98aaba476efd.PNG)
![9](https://cloud.githubusercontent.com/assets/19668228/15941156/db6ebc00-2e4c-11e6-98ba-4c29c0edc45f.PNG)
![10](https://cloud.githubusercontent.com/assets/19668228/15941157/db7087c4-2e4c-11e6-987d-08aa44534712.PNG)
![11](https://cloud.githubusercontent.com/assets/19668228/15941159/db740d54-2e4c-11e6-9401-9a94a1b97c15.PNG)
![12](https://cloud.githubusercontent.com/assets/19668228/15941163/db841104-2e4c-11e6-8658-b2570fe33192.PNG)
![13](https://cloud.githubusercontent.com/assets/19668228/15941162/db78f9f4-2e4c-11e6-8cce-6e433a642e1e.PNG)
![14](https://cloud.githubusercontent.com/assets/19668228/15941164/db8597f4-2e4c-11e6-99db-43afcec87a99.PNG)

**Comment by mrdrewkeller** [comment]
Here are some example wikis.

See if you can improve this wiki by posting an exact list of modules to enable and cleaning it up a little.

https://github.com/Netflix/Hystrix/wiki

https://github.com/jeff1evesque/machine-learning/wiki/Algorithm:-Graph-Representation

https://github.com/d3/d3/wiki

**Comment by Johns2MW** [comment]
No it's fine.

**Comment by mrdrewkeller** [comment]
@Johns2MW has added the documentation to the wiki.
